/**
 * Run state registry — Phase 04A.
 *
 * The orchestrator owns one logical "run record" per active workflow run.
 * Phase 01 stored these in a process-local Map; Phase 04A flips that to a
 * `RunStateRepo` abstraction backed by Postgres (Drizzle), with an
 * in-memory implementation kept for tests.
 *
 * Public surface (kept stable from Phase 01 so call sites don't churn):
 *   register(record)
 *   update(runId, partial)
 *   get(runId)
 *   assertWorkspaceMatch(runId, workspaceId)
 *
 * The module-level `register/update/get/assertWorkspaceMatch` exports
 * delegate to a singleton `RunStateRepo` whose impl is selected once per
 * process — Drizzle in production, in-memory under tests. Tests can swap
 * the active repo via `__setRunStateRepoForTests`.
 *
 * A small LRU on the Drizzle impl absorbs the read traffic generated by
 * SSE consumers polling for snapshots; writes invalidate the cached
 * entry so reads stay coherent.
 */

import { and, desc, eq, gte, lte, type SQL } from 'drizzle-orm'
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js'
import { getDb } from '../db/index.js'
import { runs as runsTable, type Run } from '../db/schema.js'
import { RunAccessDeniedError, RunNotFoundError } from '../lib/errors.js'

export type RunStatus =
  | 'pending'
  | 'booting'
  | 'running'
  | 'paused'
  | 'paused_by_user'
  | 'verifying'
  | 'completed'
  | 'failed'
  | 'verified'
  | 'unverified'

export interface RunRecord {
  runId: string
  workspaceId: string
  workflowId: string
  status: RunStatus
  browserbaseSessionId: string
  liveUrl: string
  startedAt: string
  completedAt?: string
}

/**
 * Filter shape for `RunStateRepo.list`. Phase 05 audit-query endpoints
 * use these — workspace filter is mandatory (the route layer derives it
 * from the JWT), the rest are optional.
 */
export interface ListRunsInput {
  workspaceId: string
  status?: string
  workflowId?: string
  /** ISO string lower bound on `started_at` (inclusive). */
  startedAfter?: string
  /** ISO string upper bound on `started_at` (inclusive). */
  startedBefore?: string
  limit?: number
  offset?: number
}

/**
 * Pluggable backing store for run records. Production wires the Drizzle
 * impl; tests use the in-memory impl so they don't need a live DB.
 */
export interface RunStateRepo {
  register(record: RunRecord): Promise<void> | void
  update(
    runId: string,
    partial: Partial<Omit<RunRecord, 'runId' | 'workspaceId'>>,
  ): Promise<RunRecord> | RunRecord
  get(runId: string): Promise<RunRecord> | RunRecord
  list(input: ListRunsInput): Promise<RunRecord[]> | RunRecord[]
}

// =============================================================================
// In-memory impl — used by every test except the ones that explicitly target
// Drizzle.
// =============================================================================

export function createMemoryRepo(): RunStateRepo & { __reset: () => void } {
  const store = new Map<string, RunRecord>()
  return {
    register(record: RunRecord) {
      store.set(record.runId, record)
    },
    update(runId, partial) {
      const cur = store.get(runId)
      if (!cur) throw new RunNotFoundError(`run not found: ${runId}`)
      const next: RunRecord = { ...cur, ...partial }
      store.set(runId, next)
      return next
    },
    get(runId) {
      const cur = store.get(runId)
      if (!cur) throw new RunNotFoundError(`run not found: ${runId}`)
      return cur
    },
    list(input: ListRunsInput) {
      const all = [...store.values()].filter((r) => {
        if (r.workspaceId !== input.workspaceId) return false
        if (input.status !== undefined && r.status !== input.status) return false
        if (
          input.workflowId !== undefined &&
          r.workflowId !== input.workflowId
        )
          return false
        if (
          input.startedAfter !== undefined &&
          new Date(r.startedAt).getTime() <
            new Date(input.startedAfter).getTime()
        )
          return false
        if (
          input.startedBefore !== undefined &&
          new Date(r.startedAt).getTime() >
            new Date(input.startedBefore).getTime()
        )
          return false
        return true
      })
      // Newest first.
      all.sort(
        (a, b) =>
          new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime(),
      )
      const start = input.offset ?? 0
      const end = input.limit !== undefined ? start + input.limit : undefined
      return all.slice(start, end)
    },
    __reset() {
      store.clear()
    },
  }
}

// =============================================================================
// Drizzle impl — writes through to runtime.runtime_runs.
//
// Phase 04A only persists the slice the rest of the API already consumes
// (status, sessionId, liveUrl, timestamps). Later phases lift more columns
// into RunRecord without breaking this shape.
// =============================================================================

const LRU_MAX = 50

function rowToRecord(row: Run): RunRecord {
  return {
    runId: row.id,
    workspaceId: row.workspaceId,
    workflowId: row.workflowId,
    status: row.status as RunStatus,
    browserbaseSessionId: row.browserbaseSessionId ?? '',
    liveUrl: row.liveUrl ?? '',
    startedAt: row.startedAt.toISOString(),
    ...(row.completedAt
      ? { completedAt: row.completedAt.toISOString() }
      : {}),
  }
}

export function createDrizzleRepo(
  dbOverride?: PostgresJsDatabase<Record<string, unknown>>,
): RunStateRepo {
  // Tiny LRU keyed by runId. JS Map preserves insertion order, so on every
  // hit we delete + re-set to bump it to most-recently-used.
  const cache = new Map<string, RunRecord>()
  const remember = (rec: RunRecord) => {
    if (cache.has(rec.runId)) cache.delete(rec.runId)
    cache.set(rec.runId, rec)
    while (cache.size > LRU_MAX) {
      const oldest = cache.keys().next().value
      if (oldest === undefined) break
      cache.delete(oldest)
    }
  }
  const invalidate = (runId: string) => cache.delete(runId)
  const db = () =>
    (dbOverride ?? (getDb() as unknown as PostgresJsDatabase<Record<string, unknown>>))

  return {
    async register(record: RunRecord) {
      // workflow_id holds either a built-in id ('hello-world',
      // 'agent-helloworld') or the UUID of a runtime_workflows row. The
      // column is text, no FK constraint, so both shapes coexist. Phase
      // 10.5 wired startRun to pass the resolved id through; prior to
      // that fix, a hard-coded 'unknown' broke the
      // GET /v1/runtime/runs?workflow_id=X filter.
      await db()
        .insert(runsTable)
        .values({
          id: record.runId,
          workspaceId: record.workspaceId,
          workflowId: record.workflowId,
          status: record.status,
          browserbaseSessionId: record.browserbaseSessionId || null,
          liveUrl: record.liveUrl || null,
          startedAt: new Date(record.startedAt),
          completedAt: record.completedAt
            ? new Date(record.completedAt)
            : null,
        })
      remember(record)
    },

    async update(runId, partial) {
      // Build the column patch. Only columns we currently model in
      // RunRecord are written — drizzle ignores undefined keys, but
      // omitting them entirely is clearer.
      const patch: Partial<typeof runsTable.$inferInsert> = {}
      if (partial.status !== undefined) patch.status = partial.status
      if (partial.browserbaseSessionId !== undefined) {
        patch.browserbaseSessionId = partial.browserbaseSessionId || null
      }
      if (partial.liveUrl !== undefined) {
        patch.liveUrl = partial.liveUrl || null
      }
      if (partial.startedAt !== undefined) {
        patch.startedAt = new Date(partial.startedAt)
      }
      if (partial.completedAt !== undefined) {
        patch.completedAt = partial.completedAt
          ? new Date(partial.completedAt)
          : null
      }

      const rows = await db()
        .update(runsTable)
        .set(patch)
        .where(eq(runsTable.id, runId))
        .returning()
      const row = rows[0]
      if (!row) throw new RunNotFoundError(`run not found: ${runId}`)
      const record = rowToRecord(row)
      invalidate(runId)
      remember(record)
      return record
    },

    async get(runId) {
      const cached = cache.get(runId)
      if (cached) {
        // LRU bump.
        cache.delete(runId)
        cache.set(runId, cached)
        return cached
      }
      const rows = await db()
        .select()
        .from(runsTable)
        .where(eq(runsTable.id, runId))
        .limit(1)
      const row = rows[0]
      if (!row) throw new RunNotFoundError(`run not found: ${runId}`)
      const record = rowToRecord(row)
      remember(record)
      return record
    },

    async list(input: ListRunsInput) {
      const filters: SQL[] = [eq(runsTable.workspaceId, input.workspaceId)]
      if (input.status !== undefined) {
        filters.push(eq(runsTable.status, input.status))
      }
      if (input.workflowId !== undefined) {
        filters.push(eq(runsTable.workflowId, input.workflowId))
      }
      if (input.startedAfter !== undefined) {
        filters.push(gte(runsTable.startedAt, new Date(input.startedAfter)))
      }
      if (input.startedBefore !== undefined) {
        filters.push(lte(runsTable.startedAt, new Date(input.startedBefore)))
      }

      let q = db()
        .select()
        .from(runsTable)
        .where(and(...filters))
        .orderBy(desc(runsTable.startedAt)) as unknown as {
        limit: (n: number) => unknown
        offset: (n: number) => unknown
      }
      if (input.limit !== undefined) q = q.limit(input.limit) as typeof q
      if (input.offset !== undefined) q = q.offset(input.offset) as typeof q
      const rows = (await (q as unknown as Promise<Run[]>)) as Run[]
      return rows.map(rowToRecord)
    },
  }
}

// Marker to signal the and(...) helper is used (drizzle's tree-shaker keeps
// it alive otherwise — explicit so future filters compose easily).
void and

// =============================================================================
// Module-level facade. Tests boot in NODE_ENV=test and get the in-memory
// impl by default; production picks Drizzle.
// =============================================================================

let activeRepo: RunStateRepo | null = null

function selectDefaultRepo(): RunStateRepo {
  // Tests rely on a shared in-memory store across `register` and the route
  // layer's `assertWorkspaceMatch`, so use the memory impl whenever
  // NODE_ENV is 'test'.
  if (process.env.NODE_ENV === 'test') return createMemoryRepo()
  return createDrizzleRepo()
}

function getRepo(): RunStateRepo {
  if (!activeRepo) activeRepo = selectDefaultRepo()
  return activeRepo
}

export async function register(record: RunRecord): Promise<void> {
  await getRepo().register(record)
}

export async function update(
  runId: string,
  partial: Partial<Omit<RunRecord, 'runId' | 'workspaceId'>>,
): Promise<RunRecord> {
  return await getRepo().update(runId, partial)
}

export async function get(runId: string): Promise<RunRecord> {
  return await getRepo().get(runId)
}

/**
 * List runs scoped to a workspace, newest first. Used by the audit-query
 * route layer; the workspaceId filter is mandatory and the route layer
 * derives it from the JWT (no cross-workspace queries possible).
 */
export async function list(input: ListRunsInput): Promise<RunRecord[]> {
  return await getRepo().list(input)
}

/**
 * Throw `RunAccessDeniedError` if the requesting workspace does not own
 * the run. Used by the SSE/snapshot routes before exposing run state.
 *
 * Returns the record on success so the caller can avoid a second lookup.
 */
export async function assertWorkspaceMatch(
  runId: string,
  workspaceId: string,
): Promise<RunRecord> {
  const r = await get(runId)
  if (r.workspaceId !== workspaceId) {
    throw new RunAccessDeniedError()
  }
  return r
}

/** Test-only: install a specific repo (e.g. a memory impl) for the duration of a test. */
export function __setRunStateRepoForTests(repo: RunStateRepo | null): void {
  activeRepo = repo
}

/**
 * Test-only: drop in-memory state. If the active repo isn't the memory
 * impl this is a no-op (tests that need to clear DB state must do so
 * themselves).
 */
export function __resetForTests(): void {
  if (activeRepo && '__reset' in activeRepo) {
    ;(activeRepo as { __reset: () => void }).__reset()
  } else {
    activeRepo = null
  }
}
