/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BrowserbaseApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BrowserbaseProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DeepgramApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleGenerativeAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RuntimeApi": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "RuntimeCronSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RuntimeScreenshotsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RuntimeVpc": {
      "type": "sst.aws.Vpc"
    }
    "SupabaseAnonKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseServiceRoleKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkspaceApiKeyHashSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkspaceJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}